wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.10
    code_path: code/train_cifar10.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.12
amp:
  desc: null
  value: true
aug:
  desc: null
  value: false
bs:
  desc: null
  value: '64'
cos:
  desc: null
  value: false
lr:
  desc: null
  value: 0.001
mixup:
  desc: null
  value: false
n_epochs:
  desc: null
  value: 50
net:
  desc: null
  value: res18
opt:
  desc: null
  value: adam
patch:
  desc: null
  value: 4
resume:
  desc: null
  value: false
scheduler:
  desc: null
  value: ReduceLROnPlateau
