wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.12
lr:
  desc: null
  value: 0.0001
net:
  desc: null
  value: res18
opt:
  desc: null
  value: adam
scheduler:
  desc: null
  value: ReduceLROnPlateau
